version: '3.1'
services:
  note-db:
    image: postgres:14-alpine
    container_name: noteDb
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=notes
      - POSTGRES_USER=bogdan
      - POSTGRES_PASSWORD=bogdan

  note-service:
    build: ./
    image: note-main-service
    container_name: note-main-service
    ports:
      - "8080:8080"
    depends_on:
      - note-db
    environment:
      - application.name=note-main
      - SPRING_DATASOURCE_URL=jdbc:postgresql://note-db:5432/notes
      - SPRING_DATASOURCE_USER=bogdan
      - SPRING_DATASOURCE_PASSWORD=bogdan
      - DB_NAME=notes
      - DB_HOST=db